# Generated by Django 4.2 on 2023-05-31 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocFormat',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor_email', models.EmailField(max_length=100)),
                ('format_type', models.CharField(max_length=100, unique=True)),
                ('FormatStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pixeltuple', models.CharField(max_length=10000, null=True)),
                ('FormatRaisedDate', models.DateTimeField(auto_now_add=True)),
                ('format_file_name', models.CharField(max_length=255)),
                ('ref_img', models.BinaryField(blank=True)),
                ('format_pproverId', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
